security:
    # https://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        chain_provider:
            chain:
                providers: [in_memory, userTemp_db, user_db]
        user_db:
            entity: { class: AppBundle\Entity\User, property: username}
        userTemp_db:
            entity: { class: AppBundle\Entity\UserTemp, property: username}
        in_memory:
            memory:
                users:
                    admin:
                        password: $2y$12$NmJuFEP1fV.wKOTboVsvqufPRO5eD6Gxg2.qN8h55na.FiUyAoNFy
                        roles: 'ROLE_ADMIN'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            provider: chain_provider
    encoders:
        Symfony\Component\Security\Core\User\UserInterface:
            algorithm: bcrypt
            cost: 12
    access_control:
            - { path: ^/admin, roles: ROLE_ADMIN }

            # activate different ways to authenticate

            # http_basic: ~
            # https://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # https://symfony.com/doc/current/cookbook/security/form_login_setup.html
