vich_uploader:
    db_driver: orm
    mappings:
        allergy:
            uri_prefix: /images/allergies
            upload_destination: '%kernel.project_dir%/public/images/allergies'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        provider:
            uri_prefix: /images/providers
            upload_destination: '%kernel.project_dir%/public/images/providers'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
 #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
