vich_uploader:
    db_driver: orm
    mappings:
        allergy:
            uri_prefix: /images/allergies
            upload_destination: '%kernel.project_dir%/public/images/allergies'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        provider:
            uri_prefix: /images/providers
            upload_destination: '%kernel.project_dir%/public/images/providers'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        product:
            uri_prefix: /images/products
            upload_destination: '%kernel.project_dir%/public/images/products'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        input:
            uri_prefix: /documents/inputs
            upload_destination: '%kernel.project_dir%/documents/inputs'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        ingredient:
            uri_prefix: /images/ingredients
            upload_destination: '%kernel.project_dir%/public/images/ingredients'
            #inject_on_load: false
            #delete_on_update: true
            #delete_on_remove: true
 #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
