#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }
acme_privacy:
    path:         /privacy
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: static/privacy.html.twig