#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }
acme_privacy:
    path:         /privacy
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: static/privacy.html.twig
logout:
    path:   /logout

dashboard:
    path:         /admin/dashboard
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: Admin/Dashboard/dashboard.html.twig

allergies:
    resource: App\Controller\Api\Allergy\AllergyController
    prefix:   /api/

api_login_check:
    path: /api/login_check